FROM ubuntu

RUN apt update
# gcc dependencies
RUN apt install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo
# other stuff used for building
RUN apt install wget

ENTRYPOINT ["bash"]
