version: "3.9"
services:
  osdev:
    build:
      context: container
      dockerfile: ../container/Containerfile
    working_dir: /mnt/osdev
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/osdev
